# Generated by Django 5.1.2 on 2024-10-29 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Price",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "$"),
                            ("EUR", "€"),
                            ("RUB", "₽"),
                            ("KZT", "лв"),
                        ],
                        default="RUB",
                        max_length=3,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "description",
                    models.TextField(max_length=500, verbose_name="Description"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField()),
                ("barcode", models.CharField(max_length=50, unique=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.price"
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.type"
                    ),
                ),
            ],
        ),
    ]
