# Generated by Django 5.1.2 on 2024-10-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_alter_price_id_alter_product_id_alter_type_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(max_length=4),
        ),
    ]
